name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build packages
        run: |
          VERSION_SUFFIX="${{ github.run_number }}-${{ github.sha }}"
          dotnet pack src/linux-dev-certs --configuration Release --output src/linux-dev-certs /p:VersionSuffix="$VERSION_SUFFIX"

      - name: Publish packages
        run: |
          dotnet nuget push -s https://www.myget.org/F/tmds/api/v2/package -k "${{ secrets.NUGET_APIKEY }}" src/linux-dev-certs/*.nupkg
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
